### ISSUE TITLE
upstream bugs: ParsingTests: Broken

### ISSUE THREAD

**Issue by frank-dspeed** [direktspeed/parse6#4]
We use mocha as testframework but that has problems with ESM Compat as it uses the ESM package to get Compat native ESM
is still not supported so the

The bug happens at present only on parsing tests it maybe has something to do with the usage of async while removing async allone ends in Memory GC.

It is not clear what exactly happens while it is clear that Package ESM  used by Mocha do not work well with Nativ ESM.

## TODO: 
- [ ] Refactor the Parsing tests.
  - [ ]  refactor dat file reader
  - [ ] refactor generate parsing tests
  - [ ]
